spring.datasource.url=jdbc:mysql://localhost:3306/awbd_prod
spring.datasource.username=awbd
spring.datasource.password=awbd

spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=never

spring.jpa.defer-datasource-initialization=true
spring.sql.init.data-locations=classpath:/data-test.sql
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE