spring.application.name=account-service
server.port=8082
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/account_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:awbd}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:awbd}
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=never
user-service.url=${USER_SERVICE_URL:http://localhost:8081}
