spring.application.name=gateway-service
server.port=8090

# Eureka client configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.prefer-ip-address=true
eureka.client.enabled=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Fast discovery polling
eureka.client.registry-fetch-interval-seconds=2
eureka.instance.lease-renewal-interval-in-seconds=2
eureka.instance.lease-expiration-duration-in-seconds=4
spring.cloud.loadbalancer.cache.ttl=2s

# OAuth2 Resource Server JWKS
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/.well-known/jwks.json

# Actuator
management.endpoints.web.exposure.include=health,info
management.info.env.enabled=true
management.endpoint.health.show-details=always

# Logging
logging.level.org.springframework.cloud.gateway=INFO
logging.level.com.example.gatewayservice=INFO
