spring.application.name=transaction-service
server.port=8083
spring.datasource.url=jdbc:mysql://localhost:3306/transaction_db
spring.datasource.username=awbd
spring.datasource.password=awbd
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never
user-service.url=http://localhost:8081
account-service.url=http://localhost:8082
bnr.url=https://www.bnr.ro/nbrfxrates.xml
