spring.application.name=transaction-service
server.port=8083
spring.profiles.active=dev
spring.jpa.show-sql=true

bnr.url=https://www.bnr.ro/nbrfxrates.xml

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.client.registry-fetch-interval-seconds=3
eureka.instance.lease-renewal-interval-in-seconds=3

management.endpoints.web.exposure.include=health,info

