spring.application.name=transaction-service
server.port=8083
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=never
user-service.url=
account-service.url=
bnr.url=
